@echo off
pip install altgraph-0.17.2-py2.py3-none-any.whl -f ./ --no-index --no-deps
pip install anyio-3.6.1-py3-none-any.whl -f ./ --no-index --no-deps
pip install certifi-2022.5.18.1-py3-none-any.whl -f ./ --no-index --no-deps
pip install click-8.1.3-py3-none-any.whl -f ./ --no-index --no-deps
pip install colorama-0.4.4-py2.py3-none-any.whl -f ./ --no-index --no-deps
pip install distlib-0.3.4-py2.py3-none-any.whl -f ./ --no-index --no-deps
pip install dnspython-2.2.1-py3-none-any.whl -f ./ --no-index --no-deps
pip install et_xmlfile-1.1.0-py3-none-any.whl -f ./ --no-index --no-deps
pip install filelock-3.7.1-py3-none-any.whl -f ./ --no-index --no-deps
pip install flash-1.0.3-py3-none-any.whl -f ./ --no-index --no-deps
pip install Flask-2.1.2-py3-none-any.whl -f ./ --no-index --no-deps
pip install Flask_WTF-1.0.1-py3-none-any.whl -f ./ --no-index --no-deps
pip install future-0.18.2.tar.gz -f ./ --no-index --no-deps
pip install greenlet-1.1.2-cp310-cp310-win_amd64.whl -f ./ --no-index --no-deps
pip install h11-0.12.0-py3-none-any.whl -f ./ --no-index --no-deps
pip install httpcore-0.15.0-py3-none-any.whl -f ./ --no-index --no-deps
pip install httpx-0.23.0-py3-none-any.whl -f ./ --no-index --no-deps
pip install idna-3.3-py3-none-any.whl -f ./ --no-index --no-deps
pip install itsdangerous-2.1.2-py3-none-any.whl -f ./ --no-index --no-deps
pip install Jinja2-3.1.2-py3-none-any.whl -f ./ --no-index --no-deps
pip install MarkupSafe-2.1.1-cp310-cp310-win_amd64.whl -f ./ --no-index --no-deps
pip install numpy-1.23.0-cp310-cp310-win_amd64.whl -f ./ --no-index --no-deps
pip install openpyxl-3.0.10-py2.py3-none-any.whl -f ./ --no-index --no-deps
pip install pefile-2022.5.30.tar.gz -f ./ --no-index --no-deps
pip install platformdirs-2.5.2-py3-none-any.whl -f ./ --no-index --no-deps
pip install ppprint-0.1.0-py3-none-any.whl -f ./ --no-index --no-deps
pip install pyhubitat-0.0.3.tar.gz -f ./ --no-index --no-deps
pip install pyinstaller-5.1-py3-none-win_amd64.whl -f ./ --no-index --no-deps
pip install pyinstaller_hooks_contrib-2022.7-py2.py3-none-any.whl -f ./ --no-index --no-deps
pip install python_dateutil-2.8.2-py2.py3-none-any.whl -f ./ --no-index --no-deps
pip install pytz-2022.1-py2.py3-none-any.whl -f ./ --no-index --no-deps
pip install pywin32_ctypes-0.2.0-py2.py3-none-any.whl -f ./ --no-index --no-deps
pip install rfc3986-1.5.0-py2.py3-none-any.whl -f ./ --no-index --no-deps
pip install setuptools-65.5.0-py3-none-any.whl -f ./ --no-index --no-deps
pip install six-1.16.0-py2.py3-none-any.whl -f ./ --no-index --no-deps
pip install sniffio-1.2.0-py3-none-any.whl -f ./ --no-index --no-deps
pip install virtualenv-20.15.1-py2.py3-none-any.whl -f ./ --no-index --no-deps
pip install Werkzeug-2.1.2-py3-none-any.whl -f ./ --no-index --no-deps
pip install WTForms-3.0.1-py3-none-any.whl -f ./ --no-index --no-deps